
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('John', 'Doe', 'EMPLOYEE', 'user1_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Jane', 'Doe', 'EMPLOYEE', 'user2_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Elvis', 'Presley', 'MANAGER', 'manager1_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Pope', 'Ofrome', 'MANAGER', 'manager2_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Papa', 'Carlo', 'ENGINEER', 'engineer1_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Ella', 'Cinder', 'ENGINEER', 'engineer2_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');

