
INSERT INTO PUBLIC.USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('John', 'Doe', 'EMPLOYEE', 'user1_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO PUBLIC.USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Jane', 'Doe', 'EMPLOYEE', 'user2_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO PUBLIC.USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Elvis', 'Presley', 'MANAGER', 'manager1_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO PUBLIC.USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Pope', 'Ofrome', 'MANAGER', 'manager2_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO PUBLIC.USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Papa', 'Carlo', 'ENGINEER', 'engineer1_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');
INSERT INTO PUBLIC.USERS (FIRST_NAME, LAST_NAME, ROLE_ID, EMAIL, PASSWORD)
VALUES ('Ella', 'Cinder', 'ENGINEER', 'engineer2_mogilev@yopmail.com', '$2a$10$1XVHOs4YjZPhAu/YwkckT.3wXD1oY2LSsFekR1cOA/6btODowO2Qi');

INSERT INTO PUBLIC.CATEGORY(NAME)
VALUES ('Application&Services');
INSERT INTO PUBLIC.CATEGORY (NAME)
VALUES ('Benefits&Paperwork');
INSERT INTO PUBLIC.CATEGORY(NAME)
VALUES ('Hardware&Software');
INSERT INTO PUBLIC.CATEGORY(NAME)
VALUES ('People Management');
INSERT INTO PUBLIC.CATEGORY(NAME)
VALUES ('Security&Access');
INSERT INTO PUBLIC.CATEGORY(NAME)
VALUES ('Workplaces&Facilities');

INSERT INTO PUBLIC.TICKET (NAME, DESCRIPTION, CREATED_ON, DESIRED_RESOLUTION_DATE, ASSIGNEE_ID, OWNER_ID, STATE_ID,
                    CATEGORY_ID, URGENCY_ID, APPROVE_ID)
VALUES ('TASK1', 'COMPUTER BROKEN', '2021-03-25', '2021-03-30', 5, 1, 'APPROVED', 3, 'LOW', 4);
INSERT INTO PUBLIC.TICKET (NAME, DESCRIPTION, CREATED_ON, DESIRED_RESOLUTION_DATE, ASSIGNEE_ID, OWNER_ID, STATE_ID,
                    CATEGORY_ID, URGENCY_ID, APPROVE_ID)
VALUES ('TASK2', 'NEED NEW TABLE', '2022-01-04', '2022-01-10', 5, 2, 'NEW', 6, 'HIGH', 4);
INSERT INTO PUBLIC.TICKET(NAME, DESCRIPTION, CREATED_ON, DESIRED_RESOLUTION_DATE, ASSIGNEE_ID, OWNER_ID, STATE_ID, CATEGORY_ID,
                   URGENCY_ID, APPROVE_ID)
VALUES ('TASK3', 'INTERNET NOT WORKING! I CANT GOOGLE!', '2022-01-24', '2022-01-25', 6, 3, 'NEW', 5, 'CRITICAL', 3);
INSERT INTO PUBLIC.TICKET(NAME, DESCRIPTION, CREATED_ON, DESIRED_RESOLUTION_DATE, ASSIGNEE_ID, OWNER_ID, STATE_ID, CATEGORY_ID,
                   URGENCY_ID, APPROVE_ID)
VALUES ('TASK4', 'PRINTER IS NOT WORKING', '2021-12-31', '2022-01-01', 6, 4, 'APPROVED', 3, 'CRITICAL', 3);
INSERT INTO PUBLIC.TICKET(NAME, DESCRIPTION, CREATED_ON, DESIRED_RESOLUTION_DATE, ASSIGNEE_ID, OWNER_ID, STATE_ID, CATEGORY_ID,
                   URGENCY_ID, APPROVE_ID)
VALUES ('TASK5', 'HEADPHONES', '2022-01-11', '2022-02-01', 5, 1, 'IN_PROGRESS', 2, 'LOW', 3);

INSERT INTO PUBLIC.HISTORY(TICKET_ID, DATE, ACTION, USER_ID, DESCRIPTION) VALUES ( 1, '2021-03-25', 'TICKET IS CREATED', 1, 'TICKET IS CREATED'  );
INSERT INTO PUBLIC.HISTORY(TICKET_ID, DATE, ACTION, USER_ID, DESCRIPTION) VALUES ( 1,'2021-03-25', 'TICKET IS EDITED', 1, 'TICKET IS EDITED' );